In [1]:
from google.colab import files
uploaded = files.upload()

Saving SampleSuperstore.csv to SampleSuperstore.csv

In [2]:
!pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.48)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2025.3)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26773 sha256=36cb1404b1722cd38817bad5e28eb16b7068a6bccb08ddfd84458fdeb2e0e9b0
  Stored in directory: /root/.cache/pip/wheels/15/a1/e7/6f92f295b5272ae5c02365e6b8fa19cb93f16a537090a1cf27
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pandasql as ps

In [5]:
def run_sql(query):
    return ps.sqldf(query, globals())

In [13]:
#Check data in SQL
query = """
SELECT *
FROM df
LIMIT 5
"""

run_sql(query)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [12]:
df = pd.read_csv('SampleSuperstore.csv')
print("DataFrame 'df' loaded successfully.")

DataFrame 'df' loaded successfully.

In [14]:
#Total Sales
query = """
SELECT SUM(Sales) AS Total_Sales
FROM df
"""

run_sql(query)

    Total_Sales
0  2.261537e+06

In [15]:
#Sales by Region
query = """
SELECT Region,
       SUM(Sales) AS Total_Sales
FROM df
GROUP BY Region
ORDER BY Total_Sales DESC
"""

run_sql(query)

    Region  Total_Sales
0     West  710219.6845
1     East  669518.7260
2  Central  492646.9132
3    South  389151.4590

In [16]:
#Sales by Category
query = """
SELECT Category,
       SUM(Sales) AS Total_Sales
FROM df
GROUP BY Category
ORDER BY Total_Sales DESC
"""

run_sql(query)

          Category  Total_Sales
0       Technology  827455.8730
1        Furniture  728658.5757
2  Office Supplies  705422.3340

In [17]:
#Top 10 Products by Sales
query = """
SELECT [Product Name],
       SUM(Sales) AS Total_Sales
FROM df
GROUP BY [Product Name]
ORDER BY Total_Sales DESC
LIMIT 10
"""

run_sql(query)

                                        Product Name  Total_Sales
0              Canon imageCLASS 2200 Advanced Copier    61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2  Cisco TelePresence System EX90 Videoconferenci...    22638.480
3       HON 5400 Series Task Chairs for Big and Tall    21870.576
4         GBC DocuBind TL300 Electric Binding System    19823.479
5   GBC Ibimaster 500 Manual ProClick Binding System    19024.500
6               Hewlett Packard LaserJet 3310 Copier    18839.686
7  HP Designjet T520 Inkjet Large Format Printer ...    18374.895
8          GBC DocuBind P400 Electric Binding System    17965.068
9        High Speed Automatic Electric Letter Opener    17030.312

In [18]:
#Sales by Customer Segment
query = """
SELECT Segment,
       SUM(Sales) AS Total_Sales
FROM df
GROUP BY Segment
ORDER BY Total_Sales DESC
"""

run_sql(query)

       Segment   Total_Sales
0     Consumer  1.148061e+06
1    Corporate  6.884941e+05
2  Home Office  4.249822e+05

In [19]:
#Top Cities by Sales
query = """
SELECT City,
       SUM(Sales) AS Total_Sales
FROM df
GROUP BY City
ORDER BY Total_Sales DESC
LIMIT 10
"""

run_sql(query)

            City  Total_Sales
0  New York City  252462.5470
1    Los Angeles  173420.1810
2        Seattle  116106.3220
3  San Francisco  109041.1200
4   Philadelphia  108841.7490
5        Houston   63956.1428
6        Chicago   47820.1330
7      San Diego   47521.0290
8   Jacksonville   44713.1830
9        Detroit   42446.9440

In [20]:
#Orders count by Ship Mode
query = """
SELECT [Ship Mode],
       COUNT(*) AS Total_Orders
FROM df
GROUP BY [Ship Mode]
ORDER BY Total_Orders DESC
"""

run_sql(query)

        Ship Mode  Total_Orders
0  Standard Class          5859
1    Second Class          1902
2     First Class          1501
3        Same Day           538

In [21]:
#Sales by State
query = """
SELECT State,
       SUM(Sales) AS Total_Sales
FROM df
GROUP BY State
ORDER BY Total_Sales DESC
LIMIT 10
"""

run_sql(query)

          State  Total_Sales
0    California  446306.4635
1      New York  306361.1470
2         Texas  168572.5322
3    Washington  135206.8500
4  Pennsylvania  116276.6500
5       Florida   88436.5320
6      Illinois   79236.5170
7      Michigan   76136.0740
8          Ohio   75130.3500
9      Virginia   70636.7200

In [22]:
#Unique Customers
query = """
SELECT COUNT(DISTINCT [Customer ID]) AS Unique_Customers
FROM df
"""

run_sql(query)

   Unique_Customers
0               793

In [23]:
#Top Customers by Sales
query = """
SELECT [Customer Name],
       SUM(Sales) AS Total_Sales
FROM df
GROUP BY [Customer Name]
ORDER BY Total_Sales DESC
LIMIT 10
"""

run_sql(query)

        Customer Name  Total_Sales
0         Sean Miller    25043.050
1        Tamara Chand    19052.218
2        Raymond Buch    15117.339
3        Tom Ashbrook    14595.620
4       Adrian Barton    14473.571
5        Ken Lonsdale    14175.229
6        Sanjit Chand    14142.334
7        Hunter Lopez    12873.298
8        Sanjit Engle    12209.438
9  Christopher Conant    12129.072